In [29]:
from MLModels import LinearRegression, LogisticRegression, UnivariantLinearRegression, LDA, PCA, KNN
import pandas as pd
import numpy as np

# Linear Regression

In [2]:
reg = LinearRegression()

x = np.array([[1,2,3],[0,1,1],[1,1,0],[1,0,1]]) # Dummy X_train
y = np.array([2.4,5.6,2.3,2.7]) # Dummy Y_train

model = LinearRegression()
model.fit(x,y)
print('Loss: ',model.loss) # Loss after final iteration

print("Y_hat: ",model.predict(np.array([1,2,3]))) # Dummy X_test

Loss:  3.6251979825350213
Y_hat:  4.109356342638097


# Logistic Regression

Specifically, the KL divergence measures a very similar quantity to cross-entropy. It measures the average number of extra bits required to represent a message with Q instead of P, not the total number of bits.

If two probability distributions are the same, then the cross-entropy between them will be the entropy of the distribution.

[All about Cross Entropy, Entropy, Kl-Divergence, Log Loss](https://machinelearningmastery.com/cross-entropy-for-machine-learning/)

**Log loss = negative log-likelihood (under a Bernoulli probability distribution)**

`Cross_Entropy(Y,Y_hat) = Log_Loss(Y,Y_hat) = Entropy(Y) + KL_Divergence(Y,Y_hat)`

`Cross_Entropy(Y,Y_hat) != Cross_Entropy(Y_hat,Y)`

In [3]:
cla = LogisticRegression()
y = np.array([1,0,0,1])
cla.fit(x,y)

print(cla.loss)

prob, cla = cla.predict(np.array([1,2,3]))
print(cla)

1.0852763569399853
1


# PCA

In [4]:
from sklearn.preprocessing import StandardScaler
from sklearn import datasets
from sklearn.decomposition import PCA as PCA_sk

iris = datasets.load_iris()
X = iris.data  # we only take the first two features.
X = StandardScaler().fit_transform(X)

pca = PCA(4)
pca.fit(X,transform=True)[:3]

array([[-2.26470281, -0.4800266 , -0.12770602,  0.0241682 ],
       [-2.08096115,  0.67413356, -0.23460885,  0.10300677],
       [-2.36422905,  0.34190802,  0.04420148,  0.02837705]])

In [5]:
pca_sk = PCA_sk(4,random_state=13)
pca_sk.fit_transform(X)[:3]

array([[-2.26470281,  0.4800266 , -0.12770602, -0.0241682 ],
       [-2.08096115, -0.67413356, -0.23460885, -0.10300677],
       [-2.36422905, -0.34190802,  0.04420148, -0.02837705]])

In [6]:
x_test = np.array([[-0.4,1.6,-0.3,1.3]])
pca.transform(x_test)

array([[-0.07919271, -1.40598311,  1.46075404,  0.61898115]])

In [7]:
pca_sk.transform(x_test)

array([[-0.07919271,  1.40598311,  1.46075404, -0.61898115]])

# KNN

In [33]:
knn = KNN(k=3)
x = np.array([[1,2,3],[3,4,5],[0,1,0]]) # Dummy X features
y = np.array([0,1,0])
x_test = np.array([[2,3,4]])

knn.fit(x,y)
knn.predict(x)

NameError: name 'X_test' is not defined